--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhiwentwest/EntityArea
build-by-default: true
branches:
- main
projects:
  EntityArea:
    path: "plugin.yml"
    icon: "icon.png"
...
