#format => name_entity: money
pdf:
 pos1:
 - 21
 - 72
 - -31
 pos2:
 - 25
 - 72
 - -42
 world: world
 entity: Zombie
 damage: 4
 health: 20
 speed: 1.00
 number: 10
 armor:
  - CHAINMAIL_HELMET
  - CHAINMAIL_CHESTPLATE
  - CHAINMAIL_LEGGINGS
  - CHAINMAIL_BOOTS

